### PR TITLE
Feat/client layoutstyling

### PR DESCRIPTION
**Pull request by kkinaman**
Implement styling based on mockups
Clean up extraneous styling code

### CODE REVIEW

**Comment by kbchun** [comment]
everything looks great! haven't gone through the code but i went through the exponent app. haha i guess only super minor thing is if we can have the homepage be static and not scrollable? other than that, looks amazing :]

**Comment by kkinaman** [comment]
Whoops haha yeah went overboard with the NativeBase Content components, forgetting they render as ScrollViews...fixing now

**Comment by kbchun** [comment]
maybe we can have the home button be located in the top right corner just for the memory details scene? that way the user has the option to either go back to viewing all memories by pressing the back button or go to home page. (note: if the user uploads/takes a pic, both the back and home button will take them to homescreen)

**Comment by kkinaman** [comment]
Good idea, I put it on the memories page too

**Pull request merged**
